export { default as HomePage } from "./HomePage";
export { default as ArticlePage } from "./ArticlePage";
export { default as SearchPage } from "./SearchPage";
export { default as CategoriesPage } from "./CategoriesPage";
export { default as CategoryPage } from "./CategoryPage";
export { default as TrendingPage } from "./TrendingPage";
export { default as AboutPage } from "./AboutPage";
export { default as PrivacyPage } from "./PrivacyPage";
export { default as NotFoundPage } from "./NotFoundPage";
